export const PHASES = [
  "Created",
  "WA msg",
  "Call",
  "No Confirmation",
  "Confirmed",
  "Check Inventory",
  "Model & DWG",
  "JO preparation",
  "Procurement",
  "Material Received",
  "JO released",
  "Cutting",
  "CNC",
  "Upholstery",
  "Shaping & Joint prep.",
  "Sand-fillet",
  "Assemble & label",
  "Paint",
  "Inspection",
  "Packaging",
  "Ready to Ship",
  "Delivered Fully"
];

export const EG_STATES: Record<string, string> = {
  "0": "Alexandria",
  "1": "Assuit",
  "2": "Aswan",
  "3": "Bani Suif",
  "4": "Behira",
  "5": "Cairo",
  "6": "Dakahlia",
  "7": "Damietta",
  "8": "El Kalioubia",
  "9": "Fayoum",
  "10": "Gharbia",
  "11": "Giza",
  "12": "Ismailia",
  "13": "Kafr Alsheikh",
  "14": "Luxor",
  "15": "Matruh",
  "16": "Minia",
  "17": "Monufia",
  "18": "New Valley",
  "19": "North Sinai",
  "20": "North Coast",
  "21": "Port Said",
  "22": "Qalyubia",
  "23": "Qena",
  "24": "Red Sea",
  "25": "Sharqia",
  "26": "Sharkia",
  "27": "Sohag",
  "28": "South Sinai",
  "29": "Suez",
  "30": "Tanta"
};
